In [1]:
import numpy as np

# Q1

In [4]:
arr = np.arange(0 , 10 , 1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr.shape

(10,)

# Q2

In [6]:
arr = np.full((3,3), fill_value= True, dtype=bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
arr = np.ones((3,3)) > 0
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
arr = np.ones((3,3), dtype=bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# Q3

In [11]:
arr = np.arange(0,10)
print(arr[arr%2 == 1])

[1 3 5 7 9]


# Q4

In [12]:
arr = np.arange(0,10)
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# Q5

In [13]:
arr = np.arange(0,10)
arr_2d = arr.reshape(2,-1)
arr_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Q6

In [14]:
arr1 = np.arange(0,10).reshape(2,-1)
arr2 = np.repeat(1, 10).reshape(2,-1)
c = np.concatenate((arr1, arr2), axis=0)
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# Q7

In [15]:
d = np.concatenate((arr1, arr2), axis=1)
d

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# Q8

In [16]:
arr = np.array([1,2,3])
print(np.repeat(arr, 3))
print(np.tile(arr, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


# Q9

In [17]:
a = np.array([2,6,1,9,10,3,27])
index = np.where((a>5)&(a<=10))
a[index]

array([ 6,  9, 10])

# Q10

In [18]:
def maxx (x , y ) :
  if x >= y :
    return x
  else :
    return y

a = np . array ([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np . array ([6 ,3 ,4 ,8 ,9 ,7 ,1])

pair_max = np . vectorize ( maxx , otypes =[ float ])
print ( pair_max (a , b ) )

[6. 7. 9. 8. 9. 7. 5.]


# Q11

In [19]:
a = np.array([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np.array([6 ,3 ,4 ,8 ,9 ,7 ,1])

print("Result", np.where(a<b,b,a))

Result [6 7 9 8 9 7 5]
