In [1]:
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 16.4MB/s]


In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv ('/content/advertising.csv')
data = df.to_numpy ()

# Q15

In [4]:
print(np.max(data[:,3]))

27.0


In [5]:
print(np.argmax(data[:,3]))

175


# Q16

In [6]:
print(np.mean(data[:,0]))

147.0425


# Q17

In [7]:
print(np.sum(data[:,3]>= 20))

40


# Q18

In [8]:
sale_bool = data[:,3]>= 15
sale_bool

array([ True, False, False,  True,  True, False, False, False, False,
        True, False,  True, False, False,  True,  True, False,  True,
       False, False,  True,  True, False,  True, False,  True,  True,
        True,  True, False,  True, False, False,  True, False,  True,
        True, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True,  True, False,  True, False,  True,  True,
        True,  True, False, False,  True,  True, False,  True,  True,
       False,  True, False, False, False,  True,  True,  True, False,
       False, False,  True, False, False, False, False, False, False,
        True, False, False,  True,  True, False,  True, False,  True,
       False, False,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False,  True,  True,  True,  True,  True, False, False, False,
       False,  True, False,  True, False,  True,  True,  True, False,
       False, False,

In [9]:
radio = data[:,1]
radio

array([37.8, 39.3, 45.9, 41.3, 10.8, 48.9, 32.8, 19.6,  2.1,  2.6,  5.8,
       24. , 35.1,  7.6, 32.9, 47.7, 36.6, 39.6, 20.5, 23.9, 27.7,  5.1,
       15.9, 16.9, 12.6,  3.5, 29.3, 16.7, 27.1, 16. , 28.3, 17.4,  1.5,
       20. ,  1.4,  4.1, 43.8, 49.4, 26.7, 37.7, 22.3, 33.4, 27.7,  8.4,
       25.7, 22.5,  9.9, 41.5, 15.8, 11.7,  3.1,  9.6, 41.7, 46.2, 28.8,
       49.4, 28.1, 19.2, 49.6, 29.5,  2. , 42.7, 15.5, 29.6, 42.8,  9.3,
       24.6, 14.5, 27.5, 43.9, 30.6, 14.3, 33. ,  5.7, 24.6, 43.7,  1.6,
       28.5, 29.9,  7.7, 26.7,  4.1, 20.3, 44.5, 43. , 18.4, 27.5, 40.6,
       25.5, 47.8,  4.9,  1.5, 33.5, 36.5, 14. , 31.6,  3.5, 21. , 42.3,
       41.7,  4.3, 36.3, 10.1, 17.2, 34.3, 46.4, 11. ,  0.3,  0.4, 26.9,
        8.2, 38. , 15.4, 20.6, 46.8, 35. , 14.3,  0.8, 36.9, 16. , 26.8,
       21.7,  2.4, 34.6, 32.3, 11.8, 38.9,  0. , 49. , 12. , 39.6,  2.9,
       27.2, 33.5, 38.6, 47. , 39. , 28.9, 25.9, 43.9, 17. , 35.4, 33.2,
        5.7, 14.8,  1.9,  7.3, 49. , 40.3, 25.8, 13

In [10]:
radio_value = radio[sale_bool]
radio_value

array([37.8, 41.3, 10.8,  2.6, 24. , 32.9, 47.7, 39.6, 27.7,  5.1, 16.9,
        3.5, 29.3, 16.7, 27.1, 28.3, 20. ,  4.1, 43.8, 37.7, 22.3, 33.4,
       27.7,  8.4, 22.5, 41.5, 15.8,  3.1, 41.7, 46.2, 28.8, 49.4, 49.6,
       29.5, 42.7, 15.5, 42.8, 27.5, 43.9, 30.6, 24.6,  4.1, 43. , 18.4,
       40.6, 47.8, 33.5, 36.5, 31.6,  3.5, 21. , 42.3, 41.7,  4.3, 36.3,
       10.1, 17.2, 34.3, 46.4, 26.9,  8.2, 38. , 15.4, 20.6, 36.9, 26.8,
        2.4, 34.6, 32.3, 49. ,  2.9, 33.5, 28.9, 43.9, 35.4, 33.2,  7.3,
       49. , 13.9, 23.3, 39.7, 21.1, 43.5, 18.1, 18.1, 36.8,  3.4,  5.2,
       23.6, 10.6, 20.9,  7.1,  3.4, 48.9, 30.2,  7.8,  2.3, 10. ,  2.6,
        5.4, 43. , 21.3, 45.1, 28.7, 13.9, 42. , 35.6, 42. ,  8.6])

In [11]:
radio_mean = np.mean(radio_value)
radio_mean

26.22293577981651

# Q19

In [12]:
newspaper_mean = data[:,2].mean()
newspaper_cond = data[:,2] > newspaper_mean
sales_data = data[:,3]
sales_cond = sales_data[newspaper_cond]
sales_cond

array([22.1, 10.4, 12. , 16.5, 17.9,  7.2,  9.2, 19. , 22.4, 12.5, 24.4,
       18. ,  5.6, 10.5, 21.4, 11.9, 14.7, 10.1, 21.5, 16.6, 17.1,  8.5,
       16.1, 10.6, 19.8,  9.7, 16.4, 22.6, 21.2, 23.7,  5.5, 23.8, 24.2,
       18.3, 12.4, 11. ,  8.7, 17.3, 11.3, 13.6, 21.7, 20.2, 16. , 12.9,
       16.7,  7.3, 19.4, 22.2, 16.9, 25.4, 17.2, 16.7, 23.8, 15. , 18.4,
       14.6, 12.6, 15.9, 15.5,  7. , 19.7,  6.6,  9.7, 17.7, 19.6, 10.8,
       20.8, 19.2, 20.1, 10.4, 12.3, 25.4, 16.1, 11.6, 16. , 15.3,  7.3,
       12.9, 16.4, 13.3, 16.9, 17.1, 17.5, 27. , 16.7, 26.2,  5.9, 25.5])

In [13]:
print(np.sum(sales_cond))

1405.1


# Q20

In [14]:
sales_mean = data[:,3].mean()
score_sales = np.where(data[:,3] < sales_mean, "Bad", np.where(data[:,3] > sales_mean, "Good", "Average"))
score_sales

array(['Good', 'Bad', 'Bad', 'Good', 'Good', 'Bad', 'Bad', 'Bad', 'Bad',
       'Good', 'Bad', 'Good', 'Bad', 'Bad', 'Good', 'Good', 'Bad', 'Good',
       'Bad', 'Bad', 'Good', 'Good', 'Bad', 'Good', 'Bad', 'Good', 'Bad',
       'Good', 'Good', 'Bad', 'Good', 'Bad', 'Bad', 'Good', 'Bad', 'Good',
       'Good', 'Bad', 'Bad', 'Good', 'Good', 'Good', 'Good', 'Good',
       'Bad', 'Good', 'Bad', 'Good', 'Good', 'Bad', 'Good', 'Bad', 'Good',
       'Good', 'Good', 'Good', 'Bad', 'Bad', 'Good', 'Good', 'Bad',
       'Good', 'Good', 'Bad', 'Good', 'Bad', 'Bad', 'Bad', 'Good', 'Good',
       'Good', 'Bad', 'Bad', 'Bad', 'Good', 'Bad', 'Bad', 'Bad', 'Bad',
       'Bad', 'Bad', 'Good', 'Bad', 'Bad', 'Good', 'Good', 'Bad', 'Good',
       'Bad', 'Good', 'Bad', 'Bad', 'Good', 'Good', 'Bad', 'Good', 'Good',
       'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good',
       'Bad', 'Bad', 'Bad', 'Bad', 'Good', 'Good', 'Good', 'Good', 'Good',
       'Bad', 'Bad', 'Bad', 'Bad', 'Good', 'Bad',

In [15]:
score_sales[7:10]

array(['Bad', 'Bad', 'Good'], dtype='<U7')

# Q21