# Q1

In [1]:
import torch
import torch . nn as nn

data = torch . Tensor ([1 , 2 , 3])
softmax_function = nn . Softmax ( dim =0)
output = softmax_function ( data )
assert round ( output [0]. item () , 2) == 0.09
output

tensor([0.0900, 0.2447, 0.6652])

# Q2

In [2]:
class CustomSoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x_exp = torch.exp(x)
        partition = x_exp.sum(0, keepdims=True)
        return x_exp / partition


data = torch . Tensor ([5 , 2 , 4])
my_softmax = CustomSoftmax ()
output = my_softmax ( data )
assert round ( output [ -1]. item () , 2) == 0.26
output

tensor([0.7054, 0.0351, 0.2595])

# Q3

In [3]:
data = torch . Tensor ([1 , 2 , 300000000])
my_softmax = CustomSoftmax ()
output = my_softmax ( data )
assert round ( output [0]. item () , 2) == 0.0
output

tensor([0., 0., nan])

# Q4

In [4]:
class CustomStableSoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x_max = torch.max(x, dim=0, keepdim=True)
        x_exp = torch.exp(x - x_max.values)
        partition = x_exp.sum(0, keepdims=True)
        return x_exp / partition

data = torch . Tensor ([1 , 2 , 3])
softmax_stable = CustomStableSoftmax ()
output = softmax_stable ( data )
assert round ( output [ -1]. item () , 2) == 0.67
output

tensor([0.0900, 0.2447, 0.6652])

# Q5

In [5]:
from abc import ABC, abstractmethod
class Person(ABC):
    def __init__(self, name, yob):
        self._name = name
        self._yob = yob

    def get_yob(self):
        return self._yob

    @abstractmethod
    def describe(self):
        pass

class Student(Person):
    def __init__(self, name:str, yob:int, grade:str):
        super().__init__(name=name, yob=yob)
        self.__grade = grade

    def describe(self):
        print(f"Student: {self._name}, Yob: {self._yob}, Grade: {self.__grade}")

class Teacher(Person):
    def __init__(self, name:str, yob:int, subject:str):
        super().__init__(name=name, yob=yob)
        self.__subject = subject

    def describe(self):
        print(f"Teacher: {self._name}, Yob: {self._yob}, Subject: {self.__subject}")

class Doctor(Person):
    def __init__(self, name:str, yob:int, specialist:str):
        super().__init__(name=name, yob=yob)
        self.__specialist = specialist

    def describe(self):
        print(f"Doctor: {self._name}, Yob: {self._yob}, Specialist: {self.__specialist}")

In [6]:
student1 = Student ( name =" studentZ2023 ", yob =2011 , grade ="6")
assert student1 . _yob == 2011
student1 . describe ()

Student:  studentZ2023 , Yob: 2011, Grade: 6


# Q6

In [7]:
teacher1 = Teacher ( name =" teacherZ2023 ", yob =1991 , subject =" History ")
assert teacher1 . _yob == 1991
teacher1 . describe ()

Teacher:  teacherZ2023 , Yob: 1991, Subject:  History 


# Q7

In [8]:
doctor1 = Doctor ( name =" doctorZ2023 ", yob =1981 , specialist =" Endocrinologists ")
assert doctor1 . _yob == 1981
doctor1 . describe ()

Doctor:  doctorZ2023 , Yob: 1981, Specialist:  Endocrinologists 


# Q8

In [9]:
class Ward:
    def __init__(self, name:str):
        self.__name = name
        self.__list_people = []

    def add_person(self, person:Person):
        self.__list_people.append(person)

    def describe(self):
        print(f"Ward: {self.__name}")
        for person in self.__list_people:
            person.describe()

    def count_doctor(self):
        count = 0
        for person in self.__list_people:
            if isinstance(person, Doctor):
                count += 1
        return count

    def sort_age(self):
        self.__list_people.sort(key=lambda x: x.get_yob(), reverse=True)

    def compute_average(self):
        count = 0
        result = 0
        for person in self.__list_people:
            if isinstance(person, Teacher):
                count += 1
                result += person.get_yob()
        return result/count

In [11]:
student1 = Student ( name =" studentA ", yob =2010 , grade ="7")
teacher1 = Teacher ( name =" teacherA ", yob =1969 , subject =" Math ")
teacher2 = Teacher ( name =" teacherB ", yob =1995 , subject =" History ")
doctor1 = Doctor ( name =" doctorA ", yob =1945 , specialist =" Endocrinologists ")
doctor2 = Doctor ( name =" doctorB ", yob =1975 , specialist =" Cardiologists ")
ward1 = Ward ( name =" Ward1 ")
ward1 . add_person ( student1 )
ward1 . add_person ( teacher1 )
ward1 . add_person ( teacher2 )
ward1 . add_person ( doctor1 )
ward1 . add_person ( doctor2 )
ward1 . count_doctor ()

2

# Q9

In [12]:
class CustomStack:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__stack = []

    def is_empty(self):
        return len(self.__stack) == 0

    def is_full(self):
        return len(self.__stack) == self.__capacity

    def pop(self):
        if self.is_empty():
            raise Exception("Underflow")
        return self.__stack.pop()

    def push(self, value):
        if self.is_full():
            raise Exception("Overflow")

        self.__stack.append(value)

    def top(self):
        if self.is_empty():
            print("Queue is empty")
            return
        return self.__stack[-1]

In [13]:
stack1 = CustomStack ( capacity =5)
stack1 . push (1)

assert stack1 . is_full () == False
stack1 . push (2)
print ( stack1 . is_full () )

False


# Q10

In [14]:
stack2 = CustomStack ( capacity =5)
stack2 . push (1)
assert stack2 . is_full () == False
stack2 . push (2)
print ( stack2 . top () )

2


# Q11

In [15]:
class CustomQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []

    def is_empty(self):
        return len(self.__queue) == 0

    def is_full(self):
        return len(self.__queue) == self.__capacity

    def dequeue(self):
        if self.is_empty():
            raise Exception("Underflow")
        return self.__queue.pop(0)

    def enqueue(self, value):
        if self.is_full():
            raise Exception("Overflow")
        self.__queue.append(value)

    def front(self):
        if self.is_empty():
            print("Queue is empty")
            return
        return self.__queue[0]

In [16]:
queue1 = CustomQueue ( capacity =5)
queue1 . enqueue (1)
assert queue1 . is_full () == False
queue1 . enqueue (2)
print ( queue1 . is_full () )

False


# Q12

In [17]:
queue2 = CustomQueue ( capacity =5)
queue2 . enqueue (1)
assert queue2 . is_full () == False
queue2 . enqueue (2)
print ( queue1 . front () )

1
